name: "❗ Security Vulnerability"
description: Report a security vulnerability
title: "❗ [VULNERABILITY] - <name>"
labels: [
  "vulnerability"
]
body:
  - type: input
    id: start_date
    attributes:
      label: "First Detection"
      description: When security finding occured?
      placeholder: "month/day/year"
    validations:
      required: true
  - type: textarea
    id: types
    attributes:
      label: "Vulnerability Type"
      description: Specify vulnerability type.
      placeholder: "#Pull Request ID"
    validations:
      required: false
  - type: dropdown
    id: tools
    attributes:
      label: "Security Tool"
      description: Which security tool found a vulnerability?
      multiple: true
      options:
        - Semgrep
        - Trivy
        - Github Branch Protection
        - Kubescape
        - Gitleaks
        - KICS
