name: "❗ Security Vulnerability"
description: Report a security vulnerability
title: "❗ [VULNERABILITY] - <name>"
labels: [
  "vulnerability"
]
body:
  - type: input
    id: start_date
    attributes:
      label: "First Detection"
      description: When security finding occured?
      placeholder: "month/day/year"
    validations:
      required: true
   - type: dropdown
    id: layers
    attributes:
      label: "MVS Layer"
      description: Part of the AppSec plan.
      multiple: true
      options:
        - Application Security
        - Cloud Security
        - Web Application Security
        - CI/CD Security
    validations:
      required: false
  - type: textarea
    id: types
    attributes:
      label: "Vulnerability Type"
      description: Specify vulnerability type.
    validations:
      required: true
  - type: dropdown
    id: tools
    attributes:
      label: "Security Tool"
      description: Which security tool found a vulnerability?
      multiple: true
      options:
        - Jit Remediation
        - Semgrep
        - Gosec
        - Bandit
        - Snyk
        - Gitleaks
        - Trufflehog
        - npm-audit
        - Nancy
        - OSV-Scanner
        - KICS
        - Trivy
        - Kubescape
        - GitHub MFA Checker
        - Github Branch Protection
        - other
    validations:
      required: true
  - type: textarea
    id: detail
    attributes:
      label: "Details"
      description: Explicit description of the vulnerability.
    validations:
      required: true
      
