name: "❗ Security Vulnerability"
description: Report a security vulnerability
title: "❗ [VULNERABILITY] - <name>"
labels: [
  "vulnerability"
]
body:
  - type: input
    id: start_date
    attributes:
      label: "First Detection"
      description: When security finding occured?
      placeholder: "month/day/year"
    validations:
      required: true
  - type: textarea
    id: types
    attributes:
      label: "Vulnerability Type"
      description: Specify vulnerability type.
      placeholder: "Used tool"
    validations:
      required: true
  - type: dropdown
    id: tools
    attributes:
      label: "Security Tool"
      description: Which security tool found a vulnerability?
      multiple: true
      options:
        - Jit Remediation
        - Semgrep
        - Gosec
        - Bandit
        - Snyk
        - Gitleaks
        - Trufflehog
        - npm-audit
        - Nancy
        - OSV-Scanner
        - KICS
        - Trivy
        - Kubescape
        - GitHub MFA Checker
        - Github Branch Protection
        - other
  - type: textarea
    id: detail
    attributes:
      label: "Details"
      description: Please enter an explicit description of the vulnerability 
      value: |
      render: bash
    validations:
      required: true
        
